wget http://www.pokeisrael.net/images/pokemon/1.gif 
wget http://www.pokeisrael.net/images/pokemon/2.gif 
wget http://www.pokeisrael.net/images/pokemon/3.gif 
wget http://www.pokeisrael.net/images/pokemon/4.gif 
wget http://www.pokeisrael.net/images/pokemon/5.gif 
wget http://www.pokeisrael.net/images/pokemon/6.gif 
wget http://www.pokeisrael.net/images/pokemon/7.gif 
wget http://www.pokeisrael.net/images/pokemon/8.gif 
wget http://www.pokeisrael.net/images/pokemon/9.gif 
wget http://www.pokeisrael.net/images/pokemon/10.gif 
wget http://www.pokeisrael.net/images/pokemon/11.gif 
wget http://www.pokeisrael.net/images/pokemon/12.gif 
wget http://www.pokeisrael.net/images/pokemon/13.gif 
wget http://www.pokeisrael.net/images/pokemon/14.gif 
wget http://www.pokeisrael.net/images/pokemon/15.gif 
wget http://www.pokeisrael.net/images/pokemon/16.gif 
wget http://www.pokeisrael.net/images/pokemon/17.gif 
wget http://www.pokeisrael.net/images/pokemon/18.gif 
wget http://www.pokeisrael.net/images/pokemon/19.gif 
wget http://www.pokeisrael.net/images/pokemon/20.gif 
wget http://www.pokeisrael.net/images/pokemon/21.gif 
wget http://www.pokeisrael.net/images/pokemon/22.gif 
wget http://www.pokeisrael.net/images/pokemon/23.gif 
wget http://www.pokeisrael.net/images/pokemon/24.gif 
wget http://www.pokeisrael.net/images/pokemon/25.gif 
wget http://www.pokeisrael.net/images/pokemon/26.gif 
wget http://www.pokeisrael.net/images/pokemon/27.gif 
wget http://www.pokeisrael.net/images/pokemon/28.gif 
wget http://www.pokeisrael.net/images/pokemon/29.gif 
wget http://www.pokeisrael.net/images/pokemon/30.gif 
wget http://www.pokeisrael.net/images/pokemon/31.gif 
wget http://www.pokeisrael.net/images/pokemon/32.gif 
wget http://www.pokeisrael.net/images/pokemon/33.gif 
wget http://www.pokeisrael.net/images/pokemon/34.gif 
wget http://www.pokeisrael.net/images/pokemon/35.gif 
wget http://www.pokeisrael.net/images/pokemon/36.gif 
wget http://www.pokeisrael.net/images/pokemon/37.gif 
wget http://www.pokeisrael.net/images/pokemon/38.gif 
wget http://www.pokeisrael.net/images/pokemon/39.gif 
wget http://www.pokeisrael.net/images/pokemon/40.gif 
wget http://www.pokeisrael.net/images/pokemon/41.gif 
wget http://www.pokeisrael.net/images/pokemon/42.gif 
wget http://www.pokeisrael.net/images/pokemon/43.gif 
wget http://www.pokeisrael.net/images/pokemon/44.gif 
wget http://www.pokeisrael.net/images/pokemon/45.gif 
wget http://www.pokeisrael.net/images/pokemon/46.gif 
wget http://www.pokeisrael.net/images/pokemon/47.gif 
wget http://www.pokeisrael.net/images/pokemon/48.gif 
wget http://www.pokeisrael.net/images/pokemon/49.gif 
wget http://www.pokeisrael.net/images/pokemon/50.gif 
wget http://www.pokeisrael.net/images/pokemon/51.gif 
wget http://www.pokeisrael.net/images/pokemon/52.gif 
wget http://www.pokeisrael.net/images/pokemon/53.gif 
wget http://www.pokeisrael.net/images/pokemon/54.gif 
wget http://www.pokeisrael.net/images/pokemon/55.gif 
wget http://www.pokeisrael.net/images/pokemon/56.gif 
wget http://www.pokeisrael.net/images/pokemon/57.gif 
wget http://www.pokeisrael.net/images/pokemon/58.gif 
wget http://www.pokeisrael.net/images/pokemon/59.gif 
wget http://www.pokeisrael.net/images/pokemon/60.gif 
wget http://www.pokeisrael.net/images/pokemon/61.gif 
wget http://www.pokeisrael.net/images/pokemon/62.gif 
wget http://www.pokeisrael.net/images/pokemon/63.gif 
wget http://www.pokeisrael.net/images/pokemon/64.gif 
wget http://www.pokeisrael.net/images/pokemon/65.gif 
wget http://www.pokeisrael.net/images/pokemon/66.gif 
wget http://www.pokeisrael.net/images/pokemon/67.gif 
wget http://www.pokeisrael.net/images/pokemon/68.gif 
wget http://www.pokeisrael.net/images/pokemon/69.gif 
wget http://www.pokeisrael.net/images/pokemon/70.gif 
wget http://www.pokeisrael.net/images/pokemon/71.gif 
wget http://www.pokeisrael.net/images/pokemon/72.gif 
wget http://www.pokeisrael.net/images/pokemon/73.gif 
wget http://www.pokeisrael.net/images/pokemon/74.gif 
wget http://www.pokeisrael.net/images/pokemon/75.gif 
wget http://www.pokeisrael.net/images/pokemon/76.gif 
wget http://www.pokeisrael.net/images/pokemon/77.gif 
wget http://www.pokeisrael.net/images/pokemon/78.gif 
wget http://www.pokeisrael.net/images/pokemon/79.gif 
wget http://www.pokeisrael.net/images/pokemon/80.gif 
wget http://www.pokeisrael.net/images/pokemon/81.gif 
wget http://www.pokeisrael.net/images/pokemon/82.gif 
wget http://www.pokeisrael.net/images/pokemon/83.gif 
wget http://www.pokeisrael.net/images/pokemon/84.gif 
wget http://www.pokeisrael.net/images/pokemon/85.gif 
wget http://www.pokeisrael.net/images/pokemon/86.gif 
wget http://www.pokeisrael.net/images/pokemon/87.gif 
wget http://www.pokeisrael.net/images/pokemon/88.gif 
wget http://www.pokeisrael.net/images/pokemon/89.gif 
wget http://www.pokeisrael.net/images/pokemon/90.gif 
wget http://www.pokeisrael.net/images/pokemon/91.gif 
wget http://www.pokeisrael.net/images/pokemon/92.gif 
wget http://www.pokeisrael.net/images/pokemon/93.gif 
wget http://www.pokeisrael.net/images/pokemon/94.gif 
wget http://www.pokeisrael.net/images/pokemon/95.gif 
wget http://www.pokeisrael.net/images/pokemon/96.gif 
wget http://www.pokeisrael.net/images/pokemon/97.gif 
wget http://www.pokeisrael.net/images/pokemon/98.gif 
wget http://www.pokeisrael.net/images/pokemon/99.gif 
wget http://www.pokeisrael.net/images/pokemon/100.gif 
wget http://www.pokeisrael.net/images/pokemon/101.gif 
wget http://www.pokeisrael.net/images/pokemon/102.gif 
wget http://www.pokeisrael.net/images/pokemon/103.gif 
wget http://www.pokeisrael.net/images/pokemon/104.gif 
wget http://www.pokeisrael.net/images/pokemon/105.gif 
wget http://www.pokeisrael.net/images/pokemon/106.gif 
wget http://www.pokeisrael.net/images/pokemon/107.gif 
wget http://www.pokeisrael.net/images/pokemon/108.gif 
wget http://www.pokeisrael.net/images/pokemon/109.gif 
wget http://www.pokeisrael.net/images/pokemon/110.gif 
wget http://www.pokeisrael.net/images/pokemon/111.gif 
wget http://www.pokeisrael.net/images/pokemon/112.gif 
wget http://www.pokeisrael.net/images/pokemon/113.gif 
wget http://www.pokeisrael.net/images/pokemon/114.gif 
wget http://www.pokeisrael.net/images/pokemon/115.gif 
wget http://www.pokeisrael.net/images/pokemon/116.gif 
wget http://www.pokeisrael.net/images/pokemon/117.gif 
wget http://www.pokeisrael.net/images/pokemon/118.gif 
wget http://www.pokeisrael.net/images/pokemon/119.gif 
wget http://www.pokeisrael.net/images/pokemon/120.gif 
wget http://www.pokeisrael.net/images/pokemon/121.gif 
wget http://www.pokeisrael.net/images/pokemon/122.gif 
wget http://www.pokeisrael.net/images/pokemon/123.gif 
wget http://www.pokeisrael.net/images/pokemon/124.gif 
wget http://www.pokeisrael.net/images/pokemon/125.gif 
wget http://www.pokeisrael.net/images/pokemon/126.gif 
wget http://www.pokeisrael.net/images/pokemon/127.gif 
wget http://www.pokeisrael.net/images/pokemon/128.gif 
wget http://www.pokeisrael.net/images/pokemon/129.gif 
wget http://www.pokeisrael.net/images/pokemon/130.gif 
wget http://www.pokeisrael.net/images/pokemon/131.gif 
wget http://www.pokeisrael.net/images/pokemon/132.gif 
wget http://www.pokeisrael.net/images/pokemon/133.gif 
wget http://www.pokeisrael.net/images/pokemon/134.gif 
wget http://www.pokeisrael.net/images/pokemon/135.gif 
wget http://www.pokeisrael.net/images/pokemon/136.gif 
wget http://www.pokeisrael.net/images/pokemon/137.gif 
wget http://www.pokeisrael.net/images/pokemon/138.gif 
wget http://www.pokeisrael.net/images/pokemon/139.gif 
wget http://www.pokeisrael.net/images/pokemon/140.gif 
wget http://www.pokeisrael.net/images/pokemon/141.gif 
wget http://www.pokeisrael.net/images/pokemon/142.gif 
wget http://www.pokeisrael.net/images/pokemon/143.gif 
wget http://www.pokeisrael.net/images/pokemon/144.gif 
wget http://www.pokeisrael.net/images/pokemon/145.gif 
wget http://www.pokeisrael.net/images/pokemon/146.gif 
wget http://www.pokeisrael.net/images/pokemon/147.gif 
wget http://www.pokeisrael.net/images/pokemon/148.gif 
wget http://www.pokeisrael.net/images/pokemon/149.gif 
wget http://www.pokeisrael.net/images/pokemon/150.gif 
wget http://www.pokeisrael.net/images/pokemon/151.gif
wget http://www.pokeisrael.net/images/pokemon/152.gif 
wget http://www.pokeisrael.net/images/pokemon/153.gif 
wget http://www.pokeisrael.net/images/pokemon/154.gif 
wget http://www.pokeisrael.net/images/pokemon/155.gif 
wget http://www.pokeisrael.net/images/pokemon/156.gif 
wget http://www.pokeisrael.net/images/pokemon/157.gif 
wget http://www.pokeisrael.net/images/pokemon/158.gif 
wget http://www.pokeisrael.net/images/pokemon/159.gif 
wget http://www.pokeisrael.net/images/pokemon/160.gif 
wget http://www.pokeisrael.net/images/pokemon/161.gif 
wget http://www.pokeisrael.net/images/pokemon/162.gif 
wget http://www.pokeisrael.net/images/pokemon/163.gif 
wget http://www.pokeisrael.net/images/pokemon/164.gif 
wget http://www.pokeisrael.net/images/pokemon/165.gif 
wget http://www.pokeisrael.net/images/pokemon/166.gif 
wget http://www.pokeisrael.net/images/pokemon/167.gif 
wget http://www.pokeisrael.net/images/pokemon/168.gif 
wget http://www.pokeisrael.net/images/pokemon/169.gif 
wget http://www.pokeisrael.net/images/pokemon/170.gif 
wget http://www.pokeisrael.net/images/pokemon/171.gif 
wget http://www.pokeisrael.net/images/pokemon/172.gif 
wget http://www.pokeisrael.net/images/pokemon/173.gif 
wget http://www.pokeisrael.net/images/pokemon/174.gif 
wget http://www.pokeisrael.net/images/pokemon/175.gif 
wget http://www.pokeisrael.net/images/pokemon/176.gif 
wget http://www.pokeisrael.net/images/pokemon/177.gif 
wget http://www.pokeisrael.net/images/pokemon/178.gif 
wget http://www.pokeisrael.net/images/pokemon/179.gif 
wget http://www.pokeisrael.net/images/pokemon/180.gif 
wget http://www.pokeisrael.net/images/pokemon/181.gif 
wget http://www.pokeisrael.net/images/pokemon/182.gif 
wget http://www.pokeisrael.net/images/pokemon/183.gif 
wget http://www.pokeisrael.net/images/pokemon/184.gif 
wget http://www.pokeisrael.net/images/pokemon/185.gif 
wget http://www.pokeisrael.net/images/pokemon/186.gif 
wget http://www.pokeisrael.net/images/pokemon/187.gif 
wget http://www.pokeisrael.net/images/pokemon/188.gif 
wget http://www.pokeisrael.net/images/pokemon/189.gif 
wget http://www.pokeisrael.net/images/pokemon/190.gif 
wget http://www.pokeisrael.net/images/pokemon/191.gif 
wget http://www.pokeisrael.net/images/pokemon/192.gif 
wget http://www.pokeisrael.net/images/pokemon/193.gif 
wget http://www.pokeisrael.net/images/pokemon/194.gif 
wget http://www.pokeisrael.net/images/pokemon/195.gif 
wget http://www.pokeisrael.net/images/pokemon/196.gif 
wget http://www.pokeisrael.net/images/pokemon/197.gif 
wget http://www.pokeisrael.net/images/pokemon/198.gif 
wget http://www.pokeisrael.net/images/pokemon/199.gif 
wget http://www.pokeisrael.net/images/pokemon/200.gif 
wget http://www.pokeisrael.net/images/pokemon/201.gif 
wget http://www.pokeisrael.net/images/pokemon/202.gif 
wget http://www.pokeisrael.net/images/pokemon/203.gif 
wget http://www.pokeisrael.net/images/pokemon/204.gif 
wget http://www.pokeisrael.net/images/pokemon/205.gif 
wget http://www.pokeisrael.net/images/pokemon/206.gif 
wget http://www.pokeisrael.net/images/pokemon/207.gif 
wget http://www.pokeisrael.net/images/pokemon/208.gif 
wget http://www.pokeisrael.net/images/pokemon/209.gif 
wget http://www.pokeisrael.net/images/pokemon/210.gif 
wget http://www.pokeisrael.net/images/pokemon/211.gif 
wget http://www.pokeisrael.net/images/pokemon/212.gif 
wget http://www.pokeisrael.net/images/pokemon/213.gif 
wget http://www.pokeisrael.net/images/pokemon/214.gif 
wget http://www.pokeisrael.net/images/pokemon/215.gif 
wget http://www.pokeisrael.net/images/pokemon/216.gif 
wget http://www.pokeisrael.net/images/pokemon/217.gif 
wget http://www.pokeisrael.net/images/pokemon/218.gif 
wget http://www.pokeisrael.net/images/pokemon/219.gif 
wget http://www.pokeisrael.net/images/pokemon/220.gif 
wget http://www.pokeisrael.net/images/pokemon/221.gif 
wget http://www.pokeisrael.net/images/pokemon/222.gif 
wget http://www.pokeisrael.net/images/pokemon/223.gif 
wget http://www.pokeisrael.net/images/pokemon/224.gif 
wget http://www.pokeisrael.net/images/pokemon/225.gif 
wget http://www.pokeisrael.net/images/pokemon/226.gif 
wget http://www.pokeisrael.net/images/pokemon/227.gif 
wget http://www.pokeisrael.net/images/pokemon/228.gif 
wget http://www.pokeisrael.net/images/pokemon/229.gif 
wget http://www.pokeisrael.net/images/pokemon/230.gif 
wget http://www.pokeisrael.net/images/pokemon/231.gif 
wget http://www.pokeisrael.net/images/pokemon/232.gif 
wget http://www.pokeisrael.net/images/pokemon/233.gif 
wget http://www.pokeisrael.net/images/pokemon/234.gif 
wget http://www.pokeisrael.net/images/pokemon/235.gif 
wget http://www.pokeisrael.net/images/pokemon/236.gif 
wget http://www.pokeisrael.net/images/pokemon/237.gif 
wget http://www.pokeisrael.net/images/pokemon/238.gif 
wget http://www.pokeisrael.net/images/pokemon/239.gif 
wget http://www.pokeisrael.net/images/pokemon/240.gif 
wget http://www.pokeisrael.net/images/pokemon/241.gif 
wget http://www.pokeisrael.net/images/pokemon/242.gif 
wget http://www.pokeisrael.net/images/pokemon/243.gif 
wget http://www.pokeisrael.net/images/pokemon/244.gif 
wget http://www.pokeisrael.net/images/pokemon/245.gif 
wget http://www.pokeisrael.net/images/pokemon/246.gif 
wget http://www.pokeisrael.net/images/pokemon/247.gif 
wget http://www.pokeisrael.net/images/pokemon/248.gif 
wget http://www.pokeisrael.net/images/pokemon/249.gif 
wget http://www.pokeisrael.net/images/pokemon/250.gif 
wget http://www.pokeisrael.net/images/pokemon/251.gif 
wget http://www.pokeisrael.net/images/pokemon/252.gif 
wget http://www.pokeisrael.net/images/pokemon/253.gif 
wget http://www.pokeisrael.net/images/pokemon/254.gif 
wget http://www.pokeisrael.net/images/pokemon/255.gif 
wget http://www.pokeisrael.net/images/pokemon/256.gif 
wget http://www.pokeisrael.net/images/pokemon/257.gif 
wget http://www.pokeisrael.net/images/pokemon/258.gif 
wget http://www.pokeisrael.net/images/pokemon/259.gif 
wget http://www.pokeisrael.net/images/pokemon/260.gif 
wget http://www.pokeisrael.net/images/pokemon/261.gif 
wget http://www.pokeisrael.net/images/pokemon/262.gif 
wget http://www.pokeisrael.net/images/pokemon/263.gif 
wget http://www.pokeisrael.net/images/pokemon/264.gif 
wget http://www.pokeisrael.net/images/pokemon/265.gif 
wget http://www.pokeisrael.net/images/pokemon/266.gif 
wget http://www.pokeisrael.net/images/pokemon/267.gif 
wget http://www.pokeisrael.net/images/pokemon/268.gif 
wget http://www.pokeisrael.net/images/pokemon/269.gif 
wget http://www.pokeisrael.net/images/pokemon/270.gif 
wget http://www.pokeisrael.net/images/pokemon/271.gif 
wget http://www.pokeisrael.net/images/pokemon/272.gif 
wget http://www.pokeisrael.net/images/pokemon/273.gif 
wget http://www.pokeisrael.net/images/pokemon/274.gif 
wget http://www.pokeisrael.net/images/pokemon/275.gif 
wget http://www.pokeisrael.net/images/pokemon/276.gif 
wget http://www.pokeisrael.net/images/pokemon/277.gif 
wget http://www.pokeisrael.net/images/pokemon/278.gif 
wget http://www.pokeisrael.net/images/pokemon/279.gif 
wget http://www.pokeisrael.net/images/pokemon/280.gif 
wget http://www.pokeisrael.net/images/pokemon/281.gif 
wget http://www.pokeisrael.net/images/pokemon/282.gif 
wget http://www.pokeisrael.net/images/pokemon/283.gif 
wget http://www.pokeisrael.net/images/pokemon/284.gif 
wget http://www.pokeisrael.net/images/pokemon/285.gif 
wget http://www.pokeisrael.net/images/pokemon/286.gif 
wget http://www.pokeisrael.net/images/pokemon/287.gif 
wget http://www.pokeisrael.net/images/pokemon/288.gif 
wget http://www.pokeisrael.net/images/pokemon/289.gif 
wget http://www.pokeisrael.net/images/pokemon/290.gif 
wget http://www.pokeisrael.net/images/pokemon/291.gif 
wget http://www.pokeisrael.net/images/pokemon/292.gif 
wget http://www.pokeisrael.net/images/pokemon/293.gif 
wget http://www.pokeisrael.net/images/pokemon/294.gif 
wget http://www.pokeisrael.net/images/pokemon/295.gif 
wget http://www.pokeisrael.net/images/pokemon/296.gif 
wget http://www.pokeisrael.net/images/pokemon/297.gif 
wget http://www.pokeisrael.net/images/pokemon/298.gif 
wget http://www.pokeisrael.net/images/pokemon/299.gif 
wget http://www.pokeisrael.net/images/pokemon/300.gif 
wget http://www.pokeisrael.net/images/pokemon/301.gif 
wget http://www.pokeisrael.net/images/pokemon/302.gif 
wget http://www.pokeisrael.net/images/pokemon/303.gif 
wget http://www.pokeisrael.net/images/pokemon/304.gif 
wget http://www.pokeisrael.net/images/pokemon/305.gif 
wget http://www.pokeisrael.net/images/pokemon/306.gif 
wget http://www.pokeisrael.net/images/pokemon/307.gif 
wget http://www.pokeisrael.net/images/pokemon/308.gif 
wget http://www.pokeisrael.net/images/pokemon/309.gif 
wget http://www.pokeisrael.net/images/pokemon/310.gif 
wget http://www.pokeisrael.net/images/pokemon/311.gif 
wget http://www.pokeisrael.net/images/pokemon/312.gif 
wget http://www.pokeisrael.net/images/pokemon/313.gif 
wget http://www.pokeisrael.net/images/pokemon/314.gif 
wget http://www.pokeisrael.net/images/pokemon/315.gif 
wget http://www.pokeisrael.net/images/pokemon/316.gif 
wget http://www.pokeisrael.net/images/pokemon/317.gif 
wget http://www.pokeisrael.net/images/pokemon/318.gif 
wget http://www.pokeisrael.net/images/pokemon/319.gif 
wget http://www.pokeisrael.net/images/pokemon/320.gif 
wget http://www.pokeisrael.net/images/pokemon/321.gif 
wget http://www.pokeisrael.net/images/pokemon/322.gif 
wget http://www.pokeisrael.net/images/pokemon/323.gif 
wget http://www.pokeisrael.net/images/pokemon/324.gif 
wget http://www.pokeisrael.net/images/pokemon/325.gif 
wget http://www.pokeisrael.net/images/pokemon/326.gif 
wget http://www.pokeisrael.net/images/pokemon/327.gif 
wget http://www.pokeisrael.net/images/pokemon/328.gif 
wget http://www.pokeisrael.net/images/pokemon/329.gif 
wget http://www.pokeisrael.net/images/pokemon/330.gif 
wget http://www.pokeisrael.net/images/pokemon/331.gif 
wget http://www.pokeisrael.net/images/pokemon/332.gif 
wget http://www.pokeisrael.net/images/pokemon/333.gif 
wget http://www.pokeisrael.net/images/pokemon/334.gif 
wget http://www.pokeisrael.net/images/pokemon/335.gif 
wget http://www.pokeisrael.net/images/pokemon/336.gif 
wget http://www.pokeisrael.net/images/pokemon/337.gif 
wget http://www.pokeisrael.net/images/pokemon/338.gif 
wget http://www.pokeisrael.net/images/pokemon/339.gif 
wget http://www.pokeisrael.net/images/pokemon/340.gif 
wget http://www.pokeisrael.net/images/pokemon/341.gif 
wget http://www.pokeisrael.net/images/pokemon/342.gif 
wget http://www.pokeisrael.net/images/pokemon/343.gif 
wget http://www.pokeisrael.net/images/pokemon/344.gif 
wget http://www.pokeisrael.net/images/pokemon/345.gif 
wget http://www.pokeisrael.net/images/pokemon/346.gif 
wget http://www.pokeisrael.net/images/pokemon/347.gif 
wget http://www.pokeisrael.net/images/pokemon/348.gif 
wget http://www.pokeisrael.net/images/pokemon/349.gif 
wget http://www.pokeisrael.net/images/pokemon/350.gif 
wget http://www.pokeisrael.net/images/pokemon/351.gif 
wget http://www.pokeisrael.net/images/pokemon/352.gif 
wget http://www.pokeisrael.net/images/pokemon/353.gif 
wget http://www.pokeisrael.net/images/pokemon/354.gif 
wget http://www.pokeisrael.net/images/pokemon/355.gif 
wget http://www.pokeisrael.net/images/pokemon/356.gif 
wget http://www.pokeisrael.net/images/pokemon/357.gif 
wget http://www.pokeisrael.net/images/pokemon/358.gif 
wget http://www.pokeisrael.net/images/pokemon/359.gif 
wget http://www.pokeisrael.net/images/pokemon/360.gif 
wget http://www.pokeisrael.net/images/pokemon/361.gif 
wget http://www.pokeisrael.net/images/pokemon/362.gif 
wget http://www.pokeisrael.net/images/pokemon/363.gif 
wget http://www.pokeisrael.net/images/pokemon/364.gif 
wget http://www.pokeisrael.net/images/pokemon/365.gif 
wget http://www.pokeisrael.net/images/pokemon/366.gif 
wget http://www.pokeisrael.net/images/pokemon/367.gif 
wget http://www.pokeisrael.net/images/pokemon/368.gif 
wget http://www.pokeisrael.net/images/pokemon/369.gif 
wget http://www.pokeisrael.net/images/pokemon/370.gif 
wget http://www.pokeisrael.net/images/pokemon/371.gif 
wget http://www.pokeisrael.net/images/pokemon/372.gif 
wget http://www.pokeisrael.net/images/pokemon/373.gif 
wget http://www.pokeisrael.net/images/pokemon/374.gif 
wget http://www.pokeisrael.net/images/pokemon/375.gif 
wget http://www.pokeisrael.net/images/pokemon/376.gif 
wget http://www.pokeisrael.net/images/pokemon/377.gif 
wget http://www.pokeisrael.net/images/pokemon/378.gif 
wget http://www.pokeisrael.net/images/pokemon/379.gif 
wget http://www.pokeisrael.net/images/pokemon/380.gif 
wget http://www.pokeisrael.net/images/pokemon/381.gif 
wget http://www.pokeisrael.net/images/pokemon/382.gif 
wget http://www.pokeisrael.net/images/pokemon/383.gif 
wget http://www.pokeisrael.net/images/pokemon/384.gif 
wget http://www.pokeisrael.net/images/pokemon/385.gif 
wget http://www.pokeisrael.net/images/pokemon/386.gif 
wget http://www.pokeisrael.net/images/pokemon/387.gif 
wget http://www.pokeisrael.net/images/pokemon/388.gif 
wget http://www.pokeisrael.net/images/pokemon/389.gif 
wget http://www.pokeisrael.net/images/pokemon/390.gif 
wget http://www.pokeisrael.net/images/pokemon/391.gif 
wget http://www.pokeisrael.net/images/pokemon/392.gif 
wget http://www.pokeisrael.net/images/pokemon/393.gif 
wget http://www.pokeisrael.net/images/pokemon/394.gif 
wget http://www.pokeisrael.net/images/pokemon/395.gif 
wget http://www.pokeisrael.net/images/pokemon/396.gif 
wget http://www.pokeisrael.net/images/pokemon/397.gif 
wget http://www.pokeisrael.net/images/pokemon/398.gif 
wget http://www.pokeisrael.net/images/pokemon/399.gif 
wget http://www.pokeisrael.net/images/pokemon/400.gif 
wget http://www.pokeisrael.net/images/pokemon/401.gif 
wget http://www.pokeisrael.net/images/pokemon/402.gif 
wget http://www.pokeisrael.net/images/pokemon/403.gif 
wget http://www.pokeisrael.net/images/pokemon/404.gif 
wget http://www.pokeisrael.net/images/pokemon/405.gif 
wget http://www.pokeisrael.net/images/pokemon/406.gif 
wget http://www.pokeisrael.net/images/pokemon/407.gif 
wget http://www.pokeisrael.net/images/pokemon/408.gif 
wget http://www.pokeisrael.net/images/pokemon/409.gif 
wget http://www.pokeisrael.net/images/pokemon/410.gif 
wget http://www.pokeisrael.net/images/pokemon/411.gif 
wget http://www.pokeisrael.net/images/pokemon/412.gif 
wget http://www.pokeisrael.net/images/pokemon/413.gif 
wget http://www.pokeisrael.net/images/pokemon/414.gif 
wget http://www.pokeisrael.net/images/pokemon/415.gif 
wget http://www.pokeisrael.net/images/pokemon/416.gif 
wget http://www.pokeisrael.net/images/pokemon/417.gif 
wget http://www.pokeisrael.net/images/pokemon/418.gif 
wget http://www.pokeisrael.net/images/pokemon/419.gif 
wget http://www.pokeisrael.net/images/pokemon/420.gif 
wget http://www.pokeisrael.net/images/pokemon/421.gif 
wget http://www.pokeisrael.net/images/pokemon/422.gif 
wget http://www.pokeisrael.net/images/pokemon/423.gif 
wget http://www.pokeisrael.net/images/pokemon/424.gif 
wget http://www.pokeisrael.net/images/pokemon/425.gif 
wget http://www.pokeisrael.net/images/pokemon/426.gif 
wget http://www.pokeisrael.net/images/pokemon/427.gif 
wget http://www.pokeisrael.net/images/pokemon/428.gif 
wget http://www.pokeisrael.net/images/pokemon/429.gif 
wget http://www.pokeisrael.net/images/pokemon/430.gif 
wget http://www.pokeisrael.net/images/pokemon/431.gif 
wget http://www.pokeisrael.net/images/pokemon/432.gif 
wget http://www.pokeisrael.net/images/pokemon/433.gif 
wget http://www.pokeisrael.net/images/pokemon/434.gif 
wget http://www.pokeisrael.net/images/pokemon/435.gif 
wget http://www.pokeisrael.net/images/pokemon/436.gif 
wget http://www.pokeisrael.net/images/pokemon/437.gif 
wget http://www.pokeisrael.net/images/pokemon/438.gif 
wget http://www.pokeisrael.net/images/pokemon/439.gif 
wget http://www.pokeisrael.net/images/pokemon/440.gif 
wget http://www.pokeisrael.net/images/pokemon/441.gif 
wget http://www.pokeisrael.net/images/pokemon/442.gif 
wget http://www.pokeisrael.net/images/pokemon/443.gif 
wget http://www.pokeisrael.net/images/pokemon/444.gif 
wget http://www.pokeisrael.net/images/pokemon/445.gif 
wget http://www.pokeisrael.net/images/pokemon/446.gif 
wget http://www.pokeisrael.net/images/pokemon/447.gif 
wget http://www.pokeisrael.net/images/pokemon/448.gif 
wget http://www.pokeisrael.net/images/pokemon/449.gif 
wget http://www.pokeisrael.net/images/pokemon/450.gif 
wget http://www.pokeisrael.net/images/pokemon/451.gif 
wget http://www.pokeisrael.net/images/pokemon/452.gif 
wget http://www.pokeisrael.net/images/pokemon/453.gif 
wget http://www.pokeisrael.net/images/pokemon/454.gif 
wget http://www.pokeisrael.net/images/pokemon/455.gif 
wget http://www.pokeisrael.net/images/pokemon/456.gif 
wget http://www.pokeisrael.net/images/pokemon/457.gif 
wget http://www.pokeisrael.net/images/pokemon/458.gif 
wget http://www.pokeisrael.net/images/pokemon/459.gif 
wget http://www.pokeisrael.net/images/pokemon/460.gif 
wget http://www.pokeisrael.net/images/pokemon/461.gif 
wget http://www.pokeisrael.net/images/pokemon/462.gif 
wget http://www.pokeisrael.net/images/pokemon/463.gif 
wget http://www.pokeisrael.net/images/pokemon/464.gif 
wget http://www.pokeisrael.net/images/pokemon/465.gif 
wget http://www.pokeisrael.net/images/pokemon/466.gif 
wget http://www.pokeisrael.net/images/pokemon/467.gif 
wget http://www.pokeisrael.net/images/pokemon/468.gif 
wget http://www.pokeisrael.net/images/pokemon/469.gif 
wget http://www.pokeisrael.net/images/pokemon/470.gif 
wget http://www.pokeisrael.net/images/pokemon/471.gif 
wget http://www.pokeisrael.net/images/pokemon/472.gif 
wget http://www.pokeisrael.net/images/pokemon/473.gif 
wget http://www.pokeisrael.net/images/pokemon/474.gif 
wget http://www.pokeisrael.net/images/pokemon/475.gif 
wget http://www.pokeisrael.net/images/pokemon/476.gif 
wget http://www.pokeisrael.net/images/pokemon/477.gif 
wget http://www.pokeisrael.net/images/pokemon/478.gif 
wget http://www.pokeisrael.net/images/pokemon/479.gif 
wget http://www.pokeisrael.net/images/pokemon/480.gif 
wget http://www.pokeisrael.net/images/pokemon/481.gif 
wget http://www.pokeisrael.net/images/pokemon/482.gif 
wget http://www.pokeisrael.net/images/pokemon/483.gif 
wget http://www.pokeisrael.net/images/pokemon/484.gif 
wget http://www.pokeisrael.net/images/pokemon/485.gif 
wget http://www.pokeisrael.net/images/pokemon/486.gif 
wget http://www.pokeisrael.net/images/pokemon/487.gif 
wget http://www.pokeisrael.net/images/pokemon/488.gif 
wget http://www.pokeisrael.net/images/pokemon/489.gif 
wget http://www.pokeisrael.net/images/pokemon/490.gif 
wget http://www.pokeisrael.net/images/pokemon/491.gif 
wget http://www.pokeisrael.net/images/pokemon/492.gif 
wget http://www.pokeisrael.net/images/pokemon/493.gif 
wget http://www.pokeisrael.net/images/pokemon/494.gif 
wget http://www.pokeisrael.net/images/pokemon/495.gif 
wget http://www.pokeisrael.net/images/pokemon/496.gif 
wget http://www.pokeisrael.net/images/pokemon/497.gif 
wget http://www.pokeisrael.net/images/pokemon/498.gif 
wget http://www.pokeisrael.net/images/pokemon/499.gif 
wget http://www.pokeisrael.net/images/pokemon/500.gif 
wget http://www.pokeisrael.net/images/pokemon/501.gif 
wget http://www.pokeisrael.net/images/pokemon/502.gif 
wget http://www.pokeisrael.net/images/pokemon/503.gif 
wget http://www.pokeisrael.net/images/pokemon/504.gif 
wget http://www.pokeisrael.net/images/pokemon/505.gif 
wget http://www.pokeisrael.net/images/pokemon/506.gif 
wget http://www.pokeisrael.net/images/pokemon/507.gif 
wget http://www.pokeisrael.net/images/pokemon/508.gif 
wget http://www.pokeisrael.net/images/pokemon/509.gif 
wget http://www.pokeisrael.net/images/pokemon/510.gif 
wget http://www.pokeisrael.net/images/pokemon/511.gif 
wget http://www.pokeisrael.net/images/pokemon/512.gif 
wget http://www.pokeisrael.net/images/pokemon/513.gif 
wget http://www.pokeisrael.net/images/pokemon/514.gif 
wget http://www.pokeisrael.net/images/pokemon/515.gif 
wget http://www.pokeisrael.net/images/pokemon/516.gif 
wget http://www.pokeisrael.net/images/pokemon/517.gif 
wget http://www.pokeisrael.net/images/pokemon/518.gif 
wget http://www.pokeisrael.net/images/pokemon/519.gif 
wget http://www.pokeisrael.net/images/pokemon/520.gif 
wget http://www.pokeisrael.net/images/pokemon/521.gif 
wget http://www.pokeisrael.net/images/pokemon/522.gif 
wget http://www.pokeisrael.net/images/pokemon/523.gif 
wget http://www.pokeisrael.net/images/pokemon/524.gif 
wget http://www.pokeisrael.net/images/pokemon/525.gif 
wget http://www.pokeisrael.net/images/pokemon/526.gif 
wget http://www.pokeisrael.net/images/pokemon/527.gif 
wget http://www.pokeisrael.net/images/pokemon/528.gif 
wget http://www.pokeisrael.net/images/pokemon/529.gif 
wget http://www.pokeisrael.net/images/pokemon/530.gif 
wget http://www.pokeisrael.net/images/pokemon/531.gif 
wget http://www.pokeisrael.net/images/pokemon/532.gif 
wget http://www.pokeisrael.net/images/pokemon/533.gif 
wget http://www.pokeisrael.net/images/pokemon/534.gif 
wget http://www.pokeisrael.net/images/pokemon/535.gif 
wget http://www.pokeisrael.net/images/pokemon/536.gif 
wget http://www.pokeisrael.net/images/pokemon/537.gif 
wget http://www.pokeisrael.net/images/pokemon/538.gif 
wget http://www.pokeisrael.net/images/pokemon/539.gif 
wget http://www.pokeisrael.net/images/pokemon/540.gif 
wget http://www.pokeisrael.net/images/pokemon/541.gif 
wget http://www.pokeisrael.net/images/pokemon/542.gif 
wget http://www.pokeisrael.net/images/pokemon/543.gif 
wget http://www.pokeisrael.net/images/pokemon/544.gif 
wget http://www.pokeisrael.net/images/pokemon/545.gif 
wget http://www.pokeisrael.net/images/pokemon/546.gif 
wget http://www.pokeisrael.net/images/pokemon/547.gif 
wget http://www.pokeisrael.net/images/pokemon/548.gif 
wget http://www.pokeisrael.net/images/pokemon/549.gif 
wget http://www.pokeisrael.net/images/pokemon/550.gif 
wget http://www.pokeisrael.net/images/pokemon/551.gif 
wget http://www.pokeisrael.net/images/pokemon/552.gif 
wget http://www.pokeisrael.net/images/pokemon/553.gif 
wget http://www.pokeisrael.net/images/pokemon/554.gif 
wget http://www.pokeisrael.net/images/pokemon/555.gif 
wget http://www.pokeisrael.net/images/pokemon/556.gif 
wget http://www.pokeisrael.net/images/pokemon/557.gif 
wget http://www.pokeisrael.net/images/pokemon/558.gif 
wget http://www.pokeisrael.net/images/pokemon/559.gif 
wget http://www.pokeisrael.net/images/pokemon/560.gif 
wget http://www.pokeisrael.net/images/pokemon/561.gif 
wget http://www.pokeisrael.net/images/pokemon/562.gif 
wget http://www.pokeisrael.net/images/pokemon/563.gif 
wget http://www.pokeisrael.net/images/pokemon/564.gif 
wget http://www.pokeisrael.net/images/pokemon/565.gif 
wget http://www.pokeisrael.net/images/pokemon/566.gif 
wget http://www.pokeisrael.net/images/pokemon/567.gif 
wget http://www.pokeisrael.net/images/pokemon/568.gif 
wget http://www.pokeisrael.net/images/pokemon/569.gif 
wget http://www.pokeisrael.net/images/pokemon/570.gif 
wget http://www.pokeisrael.net/images/pokemon/571.gif 
wget http://www.pokeisrael.net/images/pokemon/572.gif 
wget http://www.pokeisrael.net/images/pokemon/573.gif 
wget http://www.pokeisrael.net/images/pokemon/574.gif 
wget http://www.pokeisrael.net/images/pokemon/575.gif 
wget http://www.pokeisrael.net/images/pokemon/576.gif 
wget http://www.pokeisrael.net/images/pokemon/577.gif 
wget http://www.pokeisrael.net/images/pokemon/578.gif 
wget http://www.pokeisrael.net/images/pokemon/579.gif 
wget http://www.pokeisrael.net/images/pokemon/580.gif 
wget http://www.pokeisrael.net/images/pokemon/581.gif 
wget http://www.pokeisrael.net/images/pokemon/582.gif 
wget http://www.pokeisrael.net/images/pokemon/583.gif 
wget http://www.pokeisrael.net/images/pokemon/584.gif 
wget http://www.pokeisrael.net/images/pokemon/585.gif 
wget http://www.pokeisrael.net/images/pokemon/586.gif 
wget http://www.pokeisrael.net/images/pokemon/587.gif 
wget http://www.pokeisrael.net/images/pokemon/588.gif 
wget http://www.pokeisrael.net/images/pokemon/589.gif 
wget http://www.pokeisrael.net/images/pokemon/590.gif 
wget http://www.pokeisrael.net/images/pokemon/591.gif 
wget http://www.pokeisrael.net/images/pokemon/592.gif 
wget http://www.pokeisrael.net/images/pokemon/593.gif 
wget http://www.pokeisrael.net/images/pokemon/594.gif 
wget http://www.pokeisrael.net/images/pokemon/595.gif 
wget http://www.pokeisrael.net/images/pokemon/596.gif 
wget http://www.pokeisrael.net/images/pokemon/597.gif 
wget http://www.pokeisrael.net/images/pokemon/598.gif 
wget http://www.pokeisrael.net/images/pokemon/599.gif 
wget http://www.pokeisrael.net/images/pokemon/600.gif 
wget http://www.pokeisrael.net/images/pokemon/601.gif 
wget http://www.pokeisrael.net/images/pokemon/602.gif 
wget http://www.pokeisrael.net/images/pokemon/603.gif 
wget http://www.pokeisrael.net/images/pokemon/604.gif 
wget http://www.pokeisrael.net/images/pokemon/605.gif 
wget http://www.pokeisrael.net/images/pokemon/606.gif 
wget http://www.pokeisrael.net/images/pokemon/607.gif 
wget http://www.pokeisrael.net/images/pokemon/608.gif 
wget http://www.pokeisrael.net/images/pokemon/609.gif 
wget http://www.pokeisrael.net/images/pokemon/610.gif 
wget http://www.pokeisrael.net/images/pokemon/611.gif 
wget http://www.pokeisrael.net/images/pokemon/612.gif 
wget http://www.pokeisrael.net/images/pokemon/613.gif 
wget http://www.pokeisrael.net/images/pokemon/614.gif 
wget http://www.pokeisrael.net/images/pokemon/615.gif 
wget http://www.pokeisrael.net/images/pokemon/616.gif 
wget http://www.pokeisrael.net/images/pokemon/617.gif 
wget http://www.pokeisrael.net/images/pokemon/618.gif 
wget http://www.pokeisrael.net/images/pokemon/619.gif 
wget http://www.pokeisrael.net/images/pokemon/620.gif 
wget http://www.pokeisrael.net/images/pokemon/621.gif 
wget http://www.pokeisrael.net/images/pokemon/622.gif 
wget http://www.pokeisrael.net/images/pokemon/623.gif 
wget http://www.pokeisrael.net/images/pokemon/624.gif 
wget http://www.pokeisrael.net/images/pokemon/625.gif 
wget http://www.pokeisrael.net/images/pokemon/626.gif 
wget http://www.pokeisrael.net/images/pokemon/627.gif 
wget http://www.pokeisrael.net/images/pokemon/628.gif 
wget http://www.pokeisrael.net/images/pokemon/629.gif 
wget http://www.pokeisrael.net/images/pokemon/630.gif 
wget http://www.pokeisrael.net/images/pokemon/631.gif 
wget http://www.pokeisrael.net/images/pokemon/632.gif 
wget http://www.pokeisrael.net/images/pokemon/633.gif 
wget http://www.pokeisrael.net/images/pokemon/634.gif 
wget http://www.pokeisrael.net/images/pokemon/635.gif 
wget http://www.pokeisrael.net/images/pokemon/636.gif 
wget http://www.pokeisrael.net/images/pokemon/637.gif 
wget http://www.pokeisrael.net/images/pokemon/638.gif 
wget http://www.pokeisrael.net/images/pokemon/639.gif 
wget http://www.pokeisrael.net/images/pokemon/640.gif 
wget http://www.pokeisrael.net/images/pokemon/641.gif 
wget http://www.pokeisrael.net/images/pokemon/642.gif 
wget http://www.pokeisrael.net/images/pokemon/643.gif 
wget http://www.pokeisrael.net/images/pokemon/644.gif 
wget http://www.pokeisrael.net/images/pokemon/645.gif 
wget http://www.pokeisrael.net/images/pokemon/646.gif 
wget http://www.pokeisrael.net/images/pokemon/647.gif 
wget http://www.pokeisrael.net/images/pokemon/648.gif 
wget http://www.pokeisrael.net/images/pokemon/649.gif 
wget http://www.pokeisrael.net/images/pokemon/650.gif 
wget http://www.pokeisrael.net/images/pokemon/651.gif 
wget http://www.pokeisrael.net/images/pokemon/652.gif 
wget http://www.pokeisrael.net/images/pokemon/653.gif 
wget http://www.pokeisrael.net/images/pokemon/654.gif 
wget http://www.pokeisrael.net/images/pokemon/655.gif 
wget http://www.pokeisrael.net/images/pokemon/656.gif 
wget http://www.pokeisrael.net/images/pokemon/657.gif 
wget http://www.pokeisrael.net/images/pokemon/658.gif 
wget http://www.pokeisrael.net/images/pokemon/659.gif 
wget http://www.pokeisrael.net/images/pokemon/660.gif 
wget http://www.pokeisrael.net/images/pokemon/661.gif 
wget http://www.pokeisrael.net/images/pokemon/662.gif 
wget http://www.pokeisrael.net/images/pokemon/663.gif 
wget http://www.pokeisrael.net/images/pokemon/664.gif 
wget http://www.pokeisrael.net/images/pokemon/665.gif 
wget http://www.pokeisrael.net/images/pokemon/666.gif 
wget http://www.pokeisrael.net/images/pokemon/667.gif 
wget http://www.pokeisrael.net/images/pokemon/668.gif 
wget http://www.pokeisrael.net/images/pokemon/669.gif 
wget http://www.pokeisrael.net/images/pokemon/670.gif 
wget http://www.pokeisrael.net/images/pokemon/671.gif 
wget http://www.pokeisrael.net/images/pokemon/672.gif 
wget http://www.pokeisrael.net/images/pokemon/673.gif 
wget http://www.pokeisrael.net/images/pokemon/674.gif 
wget http://www.pokeisrael.net/images/pokemon/675.gif 
wget http://www.pokeisrael.net/images/pokemon/676.gif 
wget http://www.pokeisrael.net/images/pokemon/677.gif 
wget http://www.pokeisrael.net/images/pokemon/678.gif 
wget http://www.pokeisrael.net/images/pokemon/679.gif 
wget http://www.pokeisrael.net/images/pokemon/680.gif 
wget http://www.pokeisrael.net/images/pokemon/681.gif 
wget http://www.pokeisrael.net/images/pokemon/682.gif 
wget http://www.pokeisrael.net/images/pokemon/683.gif 
wget http://www.pokeisrael.net/images/pokemon/684.gif 
wget http://www.pokeisrael.net/images/pokemon/685.gif 
wget http://www.pokeisrael.net/images/pokemon/686.gif 
wget http://www.pokeisrael.net/images/pokemon/687.gif 
wget http://www.pokeisrael.net/images/pokemon/688.gif 
wget http://www.pokeisrael.net/images/pokemon/689.gif 
wget http://www.pokeisrael.net/images/pokemon/690.gif 
wget http://www.pokeisrael.net/images/pokemon/691.gif 
wget http://www.pokeisrael.net/images/pokemon/692.gif 
wget http://www.pokeisrael.net/images/pokemon/693.gif 
wget http://www.pokeisrael.net/images/pokemon/694.gif 
wget http://www.pokeisrael.net/images/pokemon/695.gif 
wget http://www.pokeisrael.net/images/pokemon/696.gif 
wget http://www.pokeisrael.net/images/pokemon/697.gif 
wget http://www.pokeisrael.net/images/pokemon/698.gif 
wget http://www.pokeisrael.net/images/pokemon/699.gif 
wget http://www.pokeisrael.net/images/pokemon/700.gif 
wget http://www.pokeisrael.net/images/pokemon/701.gif 
wget http://www.pokeisrael.net/images/pokemon/702.gif 
wget http://www.pokeisrael.net/images/pokemon/703.gif 
wget http://www.pokeisrael.net/images/pokemon/704.gif 
wget http://www.pokeisrael.net/images/pokemon/705.gif 
wget http://www.pokeisrael.net/images/pokemon/706.gif 
wget http://www.pokeisrael.net/images/pokemon/707.gif 
wget http://www.pokeisrael.net/images/pokemon/708.gif 
wget http://www.pokeisrael.net/images/pokemon/709.gif 
wget http://www.pokeisrael.net/images/pokemon/710.gif 
wget http://www.pokeisrael.net/images/pokemon/711.gif 
wget http://www.pokeisrael.net/images/pokemon/712.gif 
wget http://www.pokeisrael.net/images/pokemon/713.gif 
wget http://www.pokeisrael.net/images/pokemon/714.gif 
wget http://www.pokeisrael.net/images/pokemon/715.gif 
wget http://www.pokeisrael.net/images/pokemon/716.gif 
wget http://www.pokeisrael.net/images/pokemon/717.gif 
wget http://www.pokeisrael.net/images/pokemon/718.gif 
wget http://www.pokeisrael.net/images/pokemon/719.gif 
wget http://www.pokeisrael.net/images/pokemon/720.gif 
wget http://www.pokeisrael.net/images/pokemon/721.gif 
wget http://www.pokeisrael.net/images/pokemon/722.gif 
wget http://www.pokeisrael.net/images/pokemon/723.gif 
wget http://www.pokeisrael.net/images/pokemon/724.gif 
wget http://www.pokeisrael.net/images/pokemon/725.gif 
wget http://www.pokeisrael.net/images/pokemon/726.gif 
wget http://www.pokeisrael.net/images/pokemon/727.gif 
wget http://www.pokeisrael.net/images/pokemon/728.gif 
wget http://www.pokeisrael.net/images/pokemon/729.gif 
wget http://www.pokeisrael.net/images/pokemon/730.gif 
wget http://www.pokeisrael.net/images/pokemon/731.gif 
wget http://www.pokeisrael.net/images/pokemon/732.gif 
wget http://www.pokeisrael.net/images/pokemon/733.gif 
wget http://www.pokeisrael.net/images/pokemon/734.gif 
wget http://www.pokeisrael.net/images/pokemon/735.gif 
wget http://www.pokeisrael.net/images/pokemon/736.gif 
wget http://www.pokeisrael.net/images/pokemon/737.gif 
wget http://www.pokeisrael.net/images/pokemon/738.gif 
wget http://www.pokeisrael.net/images/pokemon/739.gif 
wget http://www.pokeisrael.net/images/pokemon/740.gif 
wget http://www.pokeisrael.net/images/pokemon/741.gif 
wget http://www.pokeisrael.net/images/pokemon/742.gif 
wget http://www.pokeisrael.net/images/pokemon/743.gif 
wget http://www.pokeisrael.net/images/pokemon/744.gif 
wget http://www.pokeisrael.net/images/pokemon/745.gif 
wget http://www.pokeisrael.net/images/pokemon/746.gif 
wget http://www.pokeisrael.net/images/pokemon/747.gif 
wget http://www.pokeisrael.net/images/pokemon/748.gif 
wget http://www.pokeisrael.net/images/pokemon/749.gif 
wget http://www.pokeisrael.net/images/pokemon/750.gif 
wget http://www.pokeisrael.net/images/pokemon/751.gif 
wget http://www.pokeisrael.net/images/pokemon/752.gif 
wget http://www.pokeisrael.net/images/pokemon/753.gif 
wget http://www.pokeisrael.net/images/pokemon/754.gif 
wget http://www.pokeisrael.net/images/pokemon/755.gif 
wget http://www.pokeisrael.net/images/pokemon/756.gif 
wget http://www.pokeisrael.net/images/pokemon/757.gif 
wget http://www.pokeisrael.net/images/pokemon/758.gif 
wget http://www.pokeisrael.net/images/pokemon/759.gif 
wget http://www.pokeisrael.net/images/pokemon/760.gif 
wget http://www.pokeisrael.net/images/pokemon/761.gif 
wget http://www.pokeisrael.net/images/pokemon/762.gif 
wget http://www.pokeisrael.net/images/pokemon/763.gif 
wget http://www.pokeisrael.net/images/pokemon/764.gif 
wget http://www.pokeisrael.net/images/pokemon/765.gif 
wget http://www.pokeisrael.net/images/pokemon/766.gif 
wget http://www.pokeisrael.net/images/pokemon/767.gif 
wget http://www.pokeisrael.net/images/pokemon/768.gif 
wget http://www.pokeisrael.net/images/pokemon/769.gif 
wget http://www.pokeisrael.net/images/pokemon/770.gif 
wget http://www.pokeisrael.net/images/pokemon/771.gif 
wget http://www.pokeisrael.net/images/pokemon/772.gif 
wget http://www.pokeisrael.net/images/pokemon/773.gif 
wget http://www.pokeisrael.net/images/pokemon/774.gif 
wget http://www.pokeisrael.net/images/pokemon/775.gif 
wget http://www.pokeisrael.net/images/pokemon/776.gif 
wget http://www.pokeisrael.net/images/pokemon/777.gif 
wget http://www.pokeisrael.net/images/pokemon/778.gif 
wget http://www.pokeisrael.net/images/pokemon/779.gif 
wget http://www.pokeisrael.net/images/pokemon/780.gif 
wget http://www.pokeisrael.net/images/pokemon/781.gif 
wget http://www.pokeisrael.net/images/pokemon/782.gif 
wget http://www.pokeisrael.net/images/pokemon/783.gif 
wget http://www.pokeisrael.net/images/pokemon/784.gif 
wget http://www.pokeisrael.net/images/pokemon/785.gif 
wget http://www.pokeisrael.net/images/pokemon/786.gif 
wget http://www.pokeisrael.net/images/pokemon/787.gif 
wget http://www.pokeisrael.net/images/pokemon/788.gif 
wget http://www.pokeisrael.net/images/pokemon/789.gif 
wget http://www.pokeisrael.net/images/pokemon/790.gif 
wget http://www.pokeisrael.net/images/pokemon/791.gif 
wget http://www.pokeisrael.net/images/pokemon/792.gif 
wget http://www.pokeisrael.net/images/pokemon/793.gif 
wget http://www.pokeisrael.net/images/pokemon/794.gif 
wget http://www.pokeisrael.net/images/pokemon/795.gif 
wget http://www.pokeisrael.net/images/pokemon/796.gif 
wget http://www.pokeisrael.net/images/pokemon/797.gif 
wget http://www.pokeisrael.net/images/pokemon/798.gif 
wget http://www.pokeisrael.net/images/pokemon/799.gif 
wget http://www.pokeisrael.net/images/pokemon/800.gif 
wget http://www.pokeisrael.net/images/pokemon/801.gif 
wget http://www.pokeisrael.net/images/pokemon/802.gif 
wget http://www.pokeisrael.net/images/pokemon/803.gif 
wget http://www.pokeisrael.net/images/pokemon/804.gif 
wget http://www.pokeisrael.net/images/pokemon/805.gif 
wget http://www.pokeisrael.net/images/pokemon/806.gif 
wget http://www.pokeisrael.net/images/pokemon/807.gif 
wget http://www.pokeisrael.net/images/pokemon/808.gif 
wget http://www.pokeisrael.net/images/pokemon/809.gif 
wget http://www.pokeisrael.net/images/pokemon/810.gif 
wget http://www.pokeisrael.net/images/pokemon/811.gif 
wget http://www.pokeisrael.net/images/pokemon/812.gif 
wget http://www.pokeisrael.net/images/pokemon/813.gif 
wget http://www.pokeisrael.net/images/pokemon/814.gif 
wget http://www.pokeisrael.net/images/pokemon/815.gif 
wget http://www.pokeisrael.net/images/pokemon/816.gif 
wget http://www.pokeisrael.net/images/pokemon/817.gif 
wget http://www.pokeisrael.net/images/pokemon/818.gif 
wget http://www.pokeisrael.net/images/pokemon/819.gif 
wget http://www.pokeisrael.net/images/pokemon/820.gif 
wget http://www.pokeisrael.net/images/pokemon/821.gif 
wget http://www.pokeisrael.net/images/pokemon/822.gif 
wget http://www.pokeisrael.net/images/pokemon/823.gif 
wget http://www.pokeisrael.net/images/pokemon/824.gif 
wget http://www.pokeisrael.net/images/pokemon/825.gif 
wget http://www.pokeisrael.net/images/pokemon/826.gif 
wget http://www.pokeisrael.net/images/pokemon/827.gif 
wget http://www.pokeisrael.net/images/pokemon/828.gif 
wget http://www.pokeisrael.net/images/pokemon/829.gif 
wget http://www.pokeisrael.net/images/pokemon/830.gif 
wget http://www.pokeisrael.net/images/pokemon/831.gif 
wget http://www.pokeisrael.net/images/pokemon/832.gif 
wget http://www.pokeisrael.net/images/pokemon/833.gif 
wget http://www.pokeisrael.net/images/pokemon/834.gif 
wget http://www.pokeisrael.net/images/pokemon/835.gif 
wget http://www.pokeisrael.net/images/pokemon/836.gif 
wget http://www.pokeisrael.net/images/pokemon/837.gif 
wget http://www.pokeisrael.net/images/pokemon/838.gif 
wget http://www.pokeisrael.net/images/pokemon/839.gif 
wget http://www.pokeisrael.net/images/pokemon/840.gif 
wget http://www.pokeisrael.net/images/pokemon/841.gif 
wget http://www.pokeisrael.net/images/pokemon/842.gif 
wget http://www.pokeisrael.net/images/pokemon/843.gif 
wget http://www.pokeisrael.net/images/pokemon/844.gif 
wget http://www.pokeisrael.net/images/pokemon/845.gif 
wget http://www.pokeisrael.net/images/pokemon/846.gif 
wget http://www.pokeisrael.net/images/pokemon/847.gif 
wget http://www.pokeisrael.net/images/pokemon/848.gif 
wget http://www.pokeisrael.net/images/pokemon/849.gif 
wget http://www.pokeisrael.net/images/pokemon/850.gif 
wget http://www.pokeisrael.net/images/pokemon/851.gif 
wget http://www.pokeisrael.net/images/pokemon/852.gif 
wget http://www.pokeisrael.net/images/pokemon/853.gif 
wget http://www.pokeisrael.net/images/pokemon/854.gif 
wget http://www.pokeisrael.net/images/pokemon/855.gif 
wget http://www.pokeisrael.net/images/pokemon/856.gif